#!/usr/bin/env python3
"""Cross-check the HIR contract against the node set and the backend anchors.

WHY THIS EXISTS
---------------
`HIR 契约` makes `docs/spec/hir-contract.md` the semantic authority for HIR nodes
and requires every backend to agree with it. That claim is only worth something
if drift is detectable without a human reading 60 entries every time. This is
the mechanical half of the judging stack (plan section 8, layer 2); the probe
(`tools/hir-parity-probe.py`) covers the behavioural half by running code.

WHY THE FIRST RUN MATTERED
--------------------------
It reported three real defects in the P0b deliverable on its first execution:
`printMulti` had no entry although the enum declares it, two statement pointers
consumed expression entry numbers so section 2 listed 45 rows while claiming 44,
and a half-semantics note cited entry 26 for a node numbered 30. Those were fixed
rather than this script being loosened. Expect it to keep finding things.

THREE SIDES, BOTH DIRECTIONS
----------------------------
    contract      sections 2 and 3 entry tables in the contract
    node set      HIRExpr / HIRStmt cases in HIRNode.swift
    impl anchors  `case .<node>` dispatch sites, per backend

    contract-without-node    an entry names a node the enum does not declare
    node-without-contract    a declared node has no contract entry
    node-without-anchor      a backend never dispatches on that node
    entry-numbering          section numbering is not a gapless 1..N
    dangling-reference       a section 2 / 3 reference resolves to nothing

EXISTENCE, NOT BEHAVIOUR
------------------------
An anchor check answers "does this backend mention the node", nothing more. A
backend can dispatch on every node and still be wrong; that is the probe's job.
Keeping the two apart is what stops this script from growing into a second,
worse parity probe.

A backend that does not exist yet is reported as absent, not as 60 gaps — the
interpreter-over-HIR engine is a later grid, and a script that cries wolf about
unbuilt code gets ignored by the time the code lands.

Usage:
    python3 tools/hir-contract-check.py
    python3 tools/hir-contract-check.py --quiet     # failures only

Exit status is 0 when every check passes, 1 otherwise.
"""

import os
import re
import sys

# Overridable so the checker itself can be exercised against a deliberately
# broken tree. A checker that is never seen to fail is indistinguishable from
# one that cannot fail.
ROOT = os.environ.get(
    "HIR_CONTRACT_ROOT",
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
)

CONTRACT = os.path.join(ROOT, "docs/spec/hir-contract.md")
NODE_FILE = os.path.join(ROOT, "Sources/PiniCore/HIR/HIRNode.swift")

# name -> (relative paths, required). A required anchor whose files are missing is
# an error; an optional one is simply reported as not-yet-present.
ANCHORS = [
    ("llvm", (["Sources/PiniCore/CodeGen/IREmitter.swift"], True)),
    ("printer", (["Sources/PiniCore/HIR/HIRPrinter.swift"], True)),
    ("interp-hir", (["Sources/PiniCore/Interpreter/HIRExecutor.swift"], False)),
]

EXPR_HEAD = "## 2. 表达式节点"
STMT_HEAD = "## 3. 语句节点"
RESERVED_HEAD = "## 4."

ROW = re.compile(r"^\|\s*(\d+)\s*\|\s*`([A-Za-z_][A-Za-z0-9_]*)")
CASE = re.compile(r"^\s+case ([A-Za-z_][A-Za-z0-9_]*)", re.M)
DISPATCH = re.compile(r"case \.([A-Za-z_][A-Za-z0-9_]*)")


def read(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def section(text, head, end):
    start = text.index(head)
    return text[start : text.index(end, start)]


def parse_contract():
    """Return (entries, order, refs, problems).

    entries maps node name -> entry number for both sections combined; the two
    sections number independently but use disjoint node names, so one map is
    unambiguous. Existence is checked here too, because the contract normally
    lives in the working tree but is regenerated by later grids.
    """
    text = read(CONTRACT)
    entries, order, problems = {}, {}, []

    for label, head, end in (
        ("expr", EXPR_HEAD, STMT_HEAD),
        ("stmt", STMT_HEAD, RESERVED_HEAD),
    ):
        block = section(text, head, end)
        nums = []
        for line in block.splitlines():
            m = ROW.match(line)
            if not m:
                continue
            num, name = int(m.group(1)), m.group(2)
            nums.append(num)
            if name in entries:
                problems.append("duplicate entry for %s" % name)
            entries[name] = num
        order[label] = nums
        want = list(range(1, len(nums) + 1))
        if nums != want:
            problems.append(
                "%s entries are not a gapless 1..%d: %s"
                % (label, len(nums), nums)
            )

    refs = set()
    for m in re.finditer(r"§2\.(\d+)", text):
        refs.add(("2", int(m.group(1))))
    for m in re.finditer(r"§3\.(\d+)", text):
        refs.add(("3", int(m.group(1))))
    # Section 2.1-2.10 are subsection numbers, not entry numbers.
    refs = {r for r in refs if not (r[0] == "2" and r[1] < 11)}

    for sec, num in sorted(refs):
        pool = order["expr"] if sec == "2" else order["stmt"]
        if num not in pool:
            problems.append("dangling reference section %s.%d" % (sec, num))

    return entries, order, refs, problems


def parse_node_set():
    text = read(NODE_FILE)
    out = {}
    for name in ("HIRExpr", "HIRStmt"):
        m = re.search(
            r"public (?:indirect )?enum %s\b.*?\n\}\n" % name, text, re.S
        )
        if not m:
            raise SystemExit("cannot find enum %s in %s" % (name, NODE_FILE))
        out[name] = set(CASE.findall(m.group(0)))
    return out


def parse_anchor(rel_paths):
    """Union of `case .<node>` names across a backend's files.

    Expression and statement cases share no names, so one flat set is enough and
    keeps the script from having to understand each backend's dispatch shape.
    """
    found, missing = set(), []
    for rel in rel_paths:
        path = os.path.join(ROOT, rel)
        if not os.path.exists(path):
            missing.append(rel)
            continue
        found |= set(DISPATCH.findall(read(path)))
    return found, missing


def main():
    quiet = "--quiet" in sys.argv

    entries, order, refs, contract_problems = parse_contract()
    node_sets = parse_node_set()
    nodes = node_sets["HIRExpr"] | node_sets["HIRStmt"]

    failures = list(contract_problems)
    notes = []

    contract_only = sorted(set(entries) - nodes)
    node_only = sorted(nodes - set(entries))
    if contract_only:
        failures.append("contract-without-node: %s" % ", ".join(contract_only))
    if node_only:
        failures.append("node-without-contract: %s" % ", ".join(node_only))

    if not quiet:
        print(
            "contract: %d expr + %d stmt = %d entries"
            % (len(order["expr"]), len(order["stmt"]), len(entries))
        )
        print(
            "code:     %d expr + %d stmt = %d cases"
            % (len(node_sets["HIRExpr"]), len(node_sets["HIRStmt"]), len(nodes))
        )
        print("references checked: %d" % len(refs))
        print()

    for name, (rel_paths, required) in ANCHORS:
        found, missing = parse_anchor(rel_paths)
        if missing and not found:
            line = "%s: not present yet (%s)" % (name, ", ".join(missing))
            (failures if required else notes).append(line)
            continue
        uncovered = sorted(nodes - found)
        if not quiet:
            print(
                "anchor %-11s covers %d/%d nodes%s"
                % (name, len(nodes) - len(uncovered), len(nodes),
                   "" if not uncovered else "  MISSING: " + ", ".join(uncovered))
            )
        if uncovered:
            failures.append(
                "node-without-anchor [%s]: %s" % (name, ", ".join(uncovered))
            )

    if not quiet:
        print()

    for line in notes:
        print("note: %s" % line)
    for line in failures:
        print("FAIL: %s" % line)

    if failures:
        print("\n%d check(s) failed" % len(failures))
        return 1
    print("hir contract check: clean")
    return 0


if __name__ == "__main__":
    sys.exit(main())
